---

- name: Gather Nexus Facts
  hosts: nxos
  connection: httpapi
  gather_facts: yes

  tasks:
    - nxos_facts:
    - name: Get The Switch Model
      debug: var=ansible_net_model
    - name: Get The Switch OS Version
      debug: var=ansible_net_version

